let shopItemsData = [
  {
    id: "aaa",
    prod_name: "Airpods",
    prod_des: "Cuffie bluetooth pratiche e alla moda.",
    prod_url: "img/01_airpods.png",
    prod_price: "139",
  },
  {
    id: "bbb",
    prod_name: "Speaker JBL",
    prod_des: "Portatile, potente, impermeabile.",
    prod_url: "img/02_speaker.png",
    prod_price: "18",
  },
  {
    id: "ccc",
    prod_name: "Cavo Iphone",
    prod_des: "Resistente, anti groviglio (2m).",
    prod_url: "img/03_cable.png",
    prod_price: "14",
  },
  {
    id: "ddd",
    prod_name: "Powerbank",
    prod_des: "Ricarica il tuo telefono ovunque sei.",
    prod_url: "img/04_powerbank.png",
    prod_price: "33",
  },
  {
    id: "eee",
    prod_name: "WebCam",
    prod_des: "Wireless, batteria di lunga durata.",
    prod_url: "img/05_cam.png",
    prod_price: "40",
  },
  {
    id: "fff",
    prod_name: "Tripod",
    prod_des: "Professionale, stabile e versatile.",
    prod_url: "img/06_tripod.png",
    prod_price: "29",
  },
  {
    id: "ggg",
    prod_name: "Visore Notturno",
    prod_des: "Ottima visibilità in ogni condizione.",
    prod_url: "img/07_night_vs.png",
    prod_price: "230",
  },
  {
    id: "hhh",
    prod_name: "FujiCam",
    prod_des: "Immortala i momenti più belli.",
    prod_url: "img/08_fuji_cam.png",
    prod_price: "89",
  },
  {
    id: "iii",
    prod_name: "Fuji Ricariche",
    prod_des: "2 box da 10 pezzi per la tua cam.",
    prod_url: "img/09_fuji_card.png",
    prod_price: "10",
  },
  {
    id: "lll",
    prod_name: "FireStick",
    prod_des: "Rendi smart la tua vecchia TV.",
    prod_url: "img/10_firestick.png",
    prod_price: "29",
  },
  {
    id: "mmm",
    prod_name: "Kindle",
    prod_des: "Porta con te tutti i tuoi libri in un solo dispositivo.",
    prod_url: "img/11_kindle.png",
    prod_price: "119",
  },
  {
    id: "nnn",
    prod_name: "Sound Bar",
    prod_des: "Potrai goderti un suono  nitido come al cinema.",
    prod_url: "img/12_soundBar.png",
    prod_price: "99",
  },
];
